server:
  port: 5000
spring:
  application:
    name: consumer_thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

feign:
  httpclient:
    enabled: true

provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 5000 #缺省为1000

logging:
  config: classpath:conf/log4j2.xml