server:
  port: 4000

spring:
  application:
    name: consumer_jsp
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

feign:
  httpclient:
    enabled: true
  #hystrix:
    #enabled: false

hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 5000 #缺省为1000

provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

logging:
  config: classpath:conf/log4j2.xml