server:
  port: 1111

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/

logging:
  config: classpath:conf/log4j2.xml